---
- name: Install Jenkins and Docker
  hosts: nginx
  vars:
    ansible_become_password: ""
    ansible_user: 'ubuntu'
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      register: apt_update

    - name: Install java
      apt:
        name: default-jre
        state: present

    - name: Install nginx
      apt:
        name: nginx
        state: present

  
    - name: Start Jenkins service
      service:
        name: ngnix
        state: started
        enabled: yes

    
